### ISSUE TITLE
public keys seems to be  wrong?

### ISSUE THREAD

**Issue by xsamsonx** [kodkeyq/secp256k1#1]
Hi,
your code looks really great.
But somehow the produced public keys are wrong.
Maybe you know what's wrong there?

uint64_t k[4] = { 0x1111111111111111, 0x1111111111111111, 0x1111111111111111, 0x1111111111111111 };
public key x:  b0f0b704075871aa684bb5b2ca5f859a28ef3cceb9615d904f355bdcb7cc0af7
public key y: 2b07f0fbdbb2f1c1a03456d6fe2c4abea67454d9683fcf2b385b6b1b8ead809c

that's wrong!

Supposed to be :
public key x: 1ef770e47e36e7aec0f209b39d217deb4490967982b3e68c20b11b13dce6ad00
public key y: 50443bf10f915fb6fc181584af301722a7cf4a3fcf1fcd24c2b4b3f12ed106b3

Thanks alot

**Comment by kodkeyq** [comment]
Hello. Reason for that is the wrong private key which cant be more than FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE FFFFFC2F (if im not wrong). Actually i have much better and faster code and will publish it soon

**Comment by kodkeyq** [comment]
My program doesnt check if private key is more than limit value

**Comment by xsamsonx** [comment]
Thanks for your reply.
Ok, but the private key is 0x11111111111111111111111111111111.
So it's not above the limit.

And what means soon, regarding your new version?

thanks

**Comment by kodkeyq** [comment]
Guess then thats maybe some bugs in code and im 100% sure i have working version on my pc. Let me some days and ill post it here. Also you can check ETHbrutforce which im not sure that works fine cause its an unfinished version.

**Comment by kodkeyq** [comment]
Hello. Now you can use new version.

And also:

Supposed to be :
public key x: 1ef770e47e36e7aec0f209b39d217deb4490967982b3e68c20b11b13dce6ad00
public key y: 50443bf10f915fb6fc181584af301722a7cf4a3fcf1fcd24c2b4b3f12ed106b3

seems to be wrong too

**Comment by kodkeyq** [comment]
From what i see now is that you print it in wrong order: low uint64_t should be high uint64_t, then key becomes correct

**Comment by xsamsonx** [comment]
Awesome....

thank you so much!!!
